plugins {
    id ("net.fabricmc.fabric-loom") version "1.16-SNAPSHOT"
    id("me.modmuss50.mod-publish-plugin") version "0.8.4"
}

repositories {}

base.archivesName = "${project.mod_id}-${project.minecraft_version}"
version = "${project.mod_version}"

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

dependencies {
    // Fabric
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation("net.fabricmc:fabric-loader:${project.loader_version}")

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${project.mixin_extra_version}")))

    // Hocon config
    include implementation("org.spongepowered:configurate-core:${hocon_version}")
    include implementation("org.spongepowered:configurate-hocon:${hocon_version}")
    include implementation("org.apache.commons:commons-text:${commons_text_version}")
    include implementation("com.typesafe:config:${typesafe_config_version}")
    include implementation("io.leangen.geantyref:geantyref:${geantyref_version}")

}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release.set(25)
}

java {
    withSourcesJar()
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

jar {
    from "LICENCE"
}

processResources {
    inputs.property "id", project.mod_id
    inputs.property "name", project.mod_name
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand(["id": project.mod_id, "name": project.mod_name, "version": project.version])
    }
}

publishMods {
    def modrinthToken = System.getenv("MODRINTH_TOKEN") ?: ""
    def curseforgeToken = System.getenv("CURSEFORGE_TOKEN") ?: ""

    file = tasks.jar.archiveFile
    dryRun = modrinthToken.isEmpty() || curseforgeToken.isEmpty()

    displayName = "[26.1] ${project.version}"
    version = "${project.version}"

    changelog = "Release notes:\nhttps://github.com/NikitaCartes/Glowing-Torchflower/releases/tag/${project.version}"
    type = STABLE
    modLoaders.add("fabric")

    def targets = ["26.1"]

    modrinth {
        projectId = "1S4LxcvL"
        accessToken = modrinthToken

        targets.forEach(minecraftVersions::add)
    }

    curseforge {
        projectId = "827288"
        accessToken = curseforgeToken

        targets.forEach(minecraftVersions::add)
    }
}